// Closed class words.  These are fast functions for parsing and handling
// the set of closed class words for the English language.  This code was generated by 
// a program I wrote, that I will post at some point.

#ifndef _CLOSED_CLASS_H_41a7_
#define _CLOSED_CLASS_H_41a7_

#include <stdlib.h>

/* closed_class.h - autogenerated */

size_t      closed_class_count(void);
size_t      closed_class_maximum_length(void);
const char *closed_class_string_at(size_t index);

/* test for the existence of the given string in this class */
const char *closed_class_contains(const char *str);

const char *closed_class_starts_with(const char *str);
const char *closed_class_ends_with(const char *str);

#endif /* _CLOSED_CLASS_H_41a7_ */
